# Generated by Django 5.2.2 on 2025-06-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_imagepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_reviews/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
