# Generated by Django 5.2.2 on 2025-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userreview',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='review',
            field=models.TextField(default='Anonymous'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
