# Generated by Django 5.2.2 on 2025-06-15 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_userreview_uploaded_at_userreview_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='review',
        ),
        migrations.AddField(
            model_name='userreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='image',
            field=models.ImageField(blank=True, default='images/default_review.jpg', null=True, upload_to='user_reviews/'),
        ),
        migrations.CreateModel(
            name='DiscussionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discussion_images/')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.discussion')),
            ],
        ),
    ]
